New header
NSecuritySolutions/frontend_next pull request #24
Opened 2024-05-24 23:16 UTC by aleksey2299-1

Переверстал хэдэр, вопрос только у нас navbar двигается за экранам или он статичный? Я рассуждал логически и на макете задний фон у навбара был под фон main, я решил что он не должен двигаться за хэдером (если это так, то надо его в отдельный компонент еще вынести)

2024-05-26 11:01 UTC, DannyOhDanny commented on src/shared/components/Breadcrumbs/ui/Breadcrumbs.tsx
> +const names = {
может это куда-то убрать в константы?

2024-05-26 11:01 UTC, DannyOhDanny commented on src/widgets/Header/ui/Header.tsx
> +const names = {
может быть это убрать в /constants?

2024-05-26 11:01 UTC, DannyOhDanny commented on src/widgets/Header/ui/Header.tsx
> +                </SocialWrapper>
не хватает отступа от дива с иконками до контейнера кнопки во всех версиях до превращения в бургер

2024-05-26 11:01 UTC, DannyOhDanny commented on src/widgets/Header/ui/styled.ts
> +const HeaderNavLink = styled(Link)`
для бургера шрифт ссылки вроде потоньше на макете
font-weight: 400;
font-size: 16px;

2024-05-26 11:01 UTC, DannyOhDanny commented on public/icons/header/burger.svg
по желанию, можно добавить анимацию - превращение трех полосок в крестик с поворотом. Будет залипательно.

2024-05-26 11:50 UTC, aleksey2299-1 commented on src/widgets/Header/ui/Header.tsx
> +                </SocialWrapper>
Потерял)

2024-05-26 13:09 UTC, NatashaSolntseva requested changes
прилипло
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/8e37c79e-323d-4c30-bf64-1f1c2a8fccb2)
уехало все под него
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/480af8a1-395b-43b6-b10c-7aa6239989f2)
когда по ссылкам переходишь, то должно свернуться меню
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/876cb06a-44c9-46fb-a3ac-e134fc1a98d5)
на мобилке только лого без текста
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/060e41ee-9e8a-47ba-a2eb-54cd0fbcba5d)
на 621 620px переходе - ключит что-то

2024-05-26 19:52 UTC, NatashaSolntseva requested changes
анимация прикольная бургера:)
я б еще сделала чтобы на мобилке меню занимало высоту экрана
и страница чтобы под открытым меню не скролилась

2024-05-26 19:52 UTC, NatashaSolntseva commented on public/icons/header/burger.svg
должен быть еще отступ снизу, когда навигация пропадает
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/1d46d4b7-920d-4816-ab43-4fc2ab8545be)

2024-05-26 19:52 UTC, NatashaSolntseva commented on public/icons/header/close.svg
будет красивее если лого и бургер будут по углам стоять, мне кажется
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/66ffb007-9375-45e3-bf9b-c1e851817aa8)

2024-05-26 20:01 UTC, aleksey2299-1 commented on public/icons/header/burger.svg
от навбара зависит, как он себя должен вести на 1920, мне нужен ответ двигается ли он вместе с хэдером или нет

2024-05-26 20:02 UTC, aleksey2299-1 commented on public/icons/header/close.svg
Не сложно сделать

2024-05-27 10:07 UTC, NatashaSolntseva commented on public/icons/header/burger.svg
на 1920 он тоже видимо прилипший, иначе навигации нет

2024-05-27 15:06 UTC, NatashaSolntseva approved these changes
ок

2024-05-27 15:06 UTC, merged