New footer
NSecuritySolutions/frontend_next pull request #26
Opened 2024-05-25 10:45 UTC by aleksey2299-1

Новый футур

2024-05-25 21:49 UTC, DannyOhDanny commented
@aleksey2299-1  а адаптив к футеру есть? Смотрю на диплой и сверяю с макетом, с 1300 как-то не так футер отображается.

2024-05-26 11:01 UTC, DannyOhDanny commented on src/shared/components/NavColumn/ui/styled.ts
> +  grid-template-columns: repeat(3, 280px);
а почему три колонки? в целом  их 4 по 280px

2024-05-26 11:01 UTC, DannyOhDanny commented on src/shared/components/NavColumn/ui/styled.ts
> +    grid-template-columns: repeat(2, 205px);
с 1300 не по макету вроде пошел футер..

2024-05-26 11:01 UTC, DannyOhDanny commented on src/shared/components/NavColumn/ui/styled.ts
> +  max-width: 280px;
на макете с 880 все ссылки исчезают, ширина контейнера 580px и он выровнен по центру.

2024-05-26 13:13 UTC, NatashaSolntseva requested changes
все слиплось
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/bafec4c5-2675-4f0d-b21d-a7499d6bce6d)
не такой вид как на макете и прилипло к правому краю
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/3aee348f-825d-44d0-a933-ed9f42efee1c)

2024-05-26 15:22 UTC, aleksey2299-1 commented on src/shared/components/NavColumn/ui/styled.ts
> +  grid-template-columns: repeat(3, 280px);
не я так изначально сделал

2024-05-26 19:57 UTC, NatashaSolntseva requested changes

2024-05-26 19:57 UTC, NatashaSolntseva commented on src/shared/components/NavColumn/ui/styled.ts
на 360 не по макету нижняя часть
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/c888c055-9a0e-4d5c-8bbe-3992e0e595dc)
телефон и почту поменять местами
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/0e1527f7-5c64-4758-adc6-bab68280977c)

2024-05-26 20:04 UTC, aleksey2299-1 commented on src/shared/components/NavColumn/ui/styled.ts
Да не я эти компоненты делал) Вы от меня просите практически переверстать эти штуки (хотя я в принципе этим и занимаюсь)

2024-05-27 15:07 UTC, NatashaSolntseva approved these changes
ок

2024-05-27 15:08 UTC, merged