Added adaptive for cardinfo
NSecuritySolutions/frontend_next pull request #27
Opened 2024-05-25 20:08 UTC by aleksey2299-1

Добавил адаптив для карточек из раздела инфо

2024-05-26 13:24 UTC, NatashaSolntseva requested changes

2024-05-26 13:24 UTC, NatashaSolntseva commented on src/widgets/Info/ui/Info.tsx
>              <BtnLink
не надо так передавать пропсами, на адаптиве он не 15 например, а 13

2024-05-26 13:24 UTC, NatashaSolntseva commented on src/widgets/Info/ui/styled.ts
> +  }
у меня мышкой не двигается, только на клавиатуру реагирует

2024-05-26 15:24 UTC, aleksey2299-1 commented on src/widgets/Info/ui/Info.tsx
>              <BtnLink
Не я этот компонент делаль, вопросы к создателю, но я сделал так, чтобы на мобилке был 13

2024-05-26 15:25 UTC, aleksey2299-1 commented on src/widgets/Info/ui/styled.ts
> +  }
так он и не для мышки

2024-05-26 19:37 UTC, NatashaSolntseva commented on src/widgets/Info/ui/styled.ts
> +  }
а для чего, для пальца?

2024-05-26 19:39 UTC, NatashaSolntseva commented on src/widgets/Info/ui/styled.ts
> +  }
просто вдруг взбредет в голову открыть маленькое окно на компе, толжно в любом случае работать

2024-05-26 20:05 UTC, aleksey2299-1 commented on src/widgets/Info/ui/styled.ts
> +  }
Таким больным людям не стоит заходить на этот сайт

2024-05-26 20:06 UTC, aleksey2299-1 commented on src/widgets/Info/ui/styled.ts
> +  }
Уже никого не должно существовать в мире с экраном меньше 1920, из расчета на то чтобы открыть на пол экрана и не увидец горизонтальный скролл

2024-05-26 20:17 UTC, aleksey2299-1 commented on src/widgets/Info/ui/styled.ts
> +  }
короче ты настаиваешь на библиотеке

2024-05-27 10:06 UTC, NatashaSolntseva commented on src/widgets/Info/ui/styled.ts
> +  }
я за то чтобы все было единобразно и работало в любых случаях

2024-05-27 15:09 UTC, NatashaSolntseva approved these changes
ок

2024-05-27 15:10 UTC, merged