Feat/adaptive for our services
NSecuritySolutions/frontend_next pull request #28
Opened 2024-05-26 23:20 UTC by DannyOhDanny

- адаптив для блока Наши сервисы

2024-05-26 23:32 UTC, aleksey2299-1 requested changes

2024-05-26 23:32 UTC, aleksey2299-1 commented on src/shared/components/CardWithText/ui/styled.ts
> +  @media (max-width: 1180px) {
1300

2024-05-26 23:32 UTC, aleksey2299-1 commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
>    @media (max-width: 880px) {
940

2024-05-26 23:32 UTC, aleksey2299-1 commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
> +    line-height: 1.2;
у кого-то проценты, у кого-то целые, на макете вообще px

2024-05-26 23:32 UTC, aleksey2299-1 commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
> +    img {
Большие сомнение на такой способ, как будто то бы насильно передаешь фуллсайз картинку, нужно убедиться, что next такое оптимизирует

2024-05-26 23:32 UTC, aleksey2299-1 commented on src/widgets/OurServices/ui/styled.ts
>    & > div:nth-child(3) {
как-то это странно выглядит

2024-05-26 23:38 UTC, DannyOhDanny commented on src/shared/components/CardWithText/ui/styled.ts
> +  @media (max-width: 1180px) {
это все с старого адаптива тянется. сейчас макет получше как то сделан для адаптивов и можно не выдумывать брейк поинты, он хорошо идет на 1180/880/620-360.я б поменяла на понятные брейкпоинты..

2024-05-26 23:41 UTC, DannyOhDanny commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
> +    line-height: 1.2;
ну line-height принимает целые, проценты,px, em. Мне figma не пишет его почти нигде...

2024-05-26 23:42 UTC, DannyOhDanny commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
> +    img {
я посмотрю, возможно это уже и не нужно

2024-05-26 23:44 UTC, DannyOhDanny commented on src/widgets/OurServices/ui/styled.ts
>    & > div:nth-child(3) {
да.. картинки разного размера, блоки разного размера.  object-fit cover в этом случае проблему не решил.. 
пришлось ручками находить эти картинки и ставить на место. Это на самом деле косяк. Будет другая картинка, она встанет криво.

2024-05-27 08:23 UTC, aleksey2299-1 commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
> +    line-height: 1.2;
Ну было бы хорошо прийти к единообразию, мне лично вариант с целыми нравится

2024-05-27 08:29 UTC, aleksey2299-1 approved these changes

2024-05-27 10:03 UTC, NatashaSolntseva requested changes

2024-05-27 10:03 UTC, NatashaSolntseva commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
чет текст не влезает
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/118d7104-bfd6-44e0-866c-94db5dc8dc1c)

2024-05-27 10:03 UTC, NatashaSolntseva commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
нужно этот компонент поправить, шрифт уменьшить для адаптива

2024-05-27 10:30 UTC, aleksey2299-1 commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
у меня эта кнопка кстати исправлена в одном из pr

2024-05-27 11:59 UTC, DannyOhDanny commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
у меня нет этого бага.. там падинг по всем сторона установлен.

2024-05-27 12:13 UTC, DannyOhDanny commented on src/shared/components/CardWithTextAndBanner/ui/styled.ts
> +    img {
посмотрела - это же не передача картинки, а изменение свойств стилей, вполне законно..

2024-05-27 15:12 UTC, NatashaSolntseva approved these changes

2024-05-27 15:12 UTC, merged