Feature/solutions adaptive
NSecuritySolutions/frontend_next pull request #38
Opened 2024-05-29 16:00 UTC by aleksey2299-1

Адаптив готовых решений на главной странице

2024-05-30 16:29 UTC, NatashaSolntseva requested changes

2024-05-30 16:29 UTC, NatashaSolntseva commented on public/icons/solutions/question.svg
![image](https://github.com/NSecuritySolutions/frontend_next/assets/84683371/d7eab384-6cd4-4a7d-8ef1-687e6ce0e571)
как-то бы тултип поправить

2024-05-31 13:40 UTC, aleksey2299-1 commented on public/icons/solutions/question.svg
надо подумац

2024-05-31 22:21 UTC, NatashaSolntseva approved these changes

2024-05-31 22:21 UTC, merged